default_platform(:android)

platform :android do
  desc "Build and upload to the Google Play Internal track as a draft"
  lane :internal do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'draft', # Keeps the release unpublished
      json_key: 'fastlane/fastlane-android-service-account.json',
      package_name: 'com.test.demoapp'
    )
  end

  desc "Build and upload to the Google Play Beta track as a draft"
  lane :beta do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'beta',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'draft', # Change to 'completed' to auto-publish
      json_key: 'fastlane/fastlane-android-service-account.json',
      package_name: 'com.test.demoapp'
    )
  end

  desc "Build and release to the Production track"
  lane :production do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'production',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'completed', # This will publish the release
      json_key: 'fastlane/fastlane-android-service-account.json',
      package_name: 'com.test.demoapp'
    )
  end
end
