default_platform(:android)

platform :android do
  desc "Upload to Google Play Internal track as draft"
  lane :internal do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'draft',
      json_key: 'fastlane/fastlane-android-service-account.json',
      package_name: 'com.test.dempapp'
    )
  end

  desc "Promote build to Beta track"
  lane :beta do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'beta',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'draft',
      json_key: 'fastlane/fastlane-android-service-account.json',
      package_name: 'com.test.demoapp'
    )
  end

  desc "Promote build to Production"
  lane :production do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'production',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'completed',
      json_key: 'fastlane/fastlane-android-service-account.json',
      package_name: 'com.test.demoapp'
    )
  end
end
